DROP TABLE IF EXISTS Soundfront.SongTag;
DROP TABLE IF EXISTS Soundfront.Tag;
DROP TABLE IF EXISTS Soundfront.SongRating;
DROP TABLE IF EXISTS Soundfront.AlbumRating;
DROP TABLE IF EXISTS Soundfront.MusicCart;
DROP TABLE IF EXISTS Soundfront.Song;
DROP TABLE IF EXISTS Soundfront.Album;
DROP TABLE IF EXISTS Soundfront.Social;
DROP TABLE IF EXISTS Soundfront.Cart;
DROP TABLE IF EXISTS Soundfront.[User];
DROP TABLE IF EXISTS Soundfront.SongCart;
DROP TABLE IF EXISTS Soundfront.AlbumCart;

DROP SCHEMA IF EXISTS Soundfront;
GO

CREATE SCHEMA Soundfront;
GO

CREATE TABLE Soundfront.[User]
(
  UserID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Privacy BIT NOT NULL,
  LastLoginDate DATETIME NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
  JoinDate DATETIME NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
  DisplayName NVARCHAR(50) NOT NULL,
  Email NVARCHAR(50) NOT NULL,
  PasswordHash BINARY(512) NOT NULL,
  --CartID INT NOT NULL, -- FOREIGN KEY
  --  REFERENCES Soundfront.Cart(CartID)

   UNIQUE(Email)
);

CREATE TABLE Soundfront.Cart
(
  CartID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  UserID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.[User](UserID),

  UNIQUE(UserID)
);

CREATE TABLE Soundfront.Social
(
  SocialID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  FollowerID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.[User](UserID),
  FollowingID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.[User](UserID),

  UNIQUE(FollowerID, FollowingID)
);

CREATE TABLE Soundfront.Album
(
  AlbumID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  UserID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.[User](UserID),
  Title NVARCHAR(50) NOT NULL,
  AlbumArt NVARCHAR(256) NOT NULL,
  Price DECIMAL NOT NULL,
  UploadDate DATETIME NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
  Description NVARCHAR(1024) NOT NULL
);

CREATE TABLE Soundfront.Song
(
  SongID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  UserID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.[User](UserID),
  AlbumID INT FOREIGN KEY
    REFERENCES Soundfront.Album(AlbumID),
  Title NVARCHAR(50) NOT NULL,
  Length INT NOT NULL,
  UploadDate DATETIME NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
  Price DECIMAL NOT NULL,
  Description NVARCHAR(1024) NOT NULL
);

CREATE TABLE Soundfront.SongCart
(
  SongCartID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  SongID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Song(SongID),
  CartID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Cart(CartID)

  UNIQUE(SongID, CartID)
);

CREATE TABLE Soundfront.AlbumCart
(
  AlbumCartID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  AlbumID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Album(AlbumID),
  CartID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Cart(CartID)

  UNIQUE(AlbumID, CartID)
);

CREATE TABLE Soundfront.AlbumRating
(
  RatingID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  UserID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.[User](UserID),
  AlbumID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Album(AlbumID),
  Rating FLOAT NOT NULL,
  ReviewText NVARCHAR(1024) NOT NULL,

  UNIQUE(AlbumID, UserID)
);

CREATE TABLE Soundfront.SongRating
(
  RatingID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  UserID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.[User](UserID),
  SongID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Song(SongID),
  Rating FLOAT NOT NULL,
  ReviewText NVARCHAR(1024) NOT NULL,

  UNIQUE(SongID, UserID)
);

CREATE TABLE Soundfront.Tag
(
  TagID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  [Name] NVARCHAR(50) NOT NULL,

  UNIQUE([Name])
);

CREATE TABLE Soundfront.SongTag
(
  SongTagID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  TagID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Tag(TagID),
  SongID INT NOT NULL FOREIGN KEY
    REFERENCES Soundfront.Song(SongID)

  UNIQUE(TagID, SongID)
);
